#!/bin/bash
#SBATCH -JMSPARCtesting_suite
#SBATCH --account=hive-phanish6
#SBATCH -phive
#SBATCH -N 1 --ntasks-per-node=1
#SBATCH --mem-per-cpu=30G
#SBATCH -t13:00:00


cd $SLURM_SUBMIT_DIR

module load matlab

echo $PWD 



