#!/bin/bash
#SBATCH -JMLFF_train_spacegroup
#SBATCH --account=gts-phanish6-coda20
#SBATCH -p inferno
#SBATCH -N 1 --ntasks-per-node=1
#SBATCH --mem-per-cpu=30G
#SBATCH -t16:00:00


cd $SLURM_SUBMIT_DIR

module load matlab

echo $PWD 



