#!/bin/bash
#SBATCH -JMSPARCtesting_suite
#SBATCH --account=hive-phanish6
#SBATCH -phive-interact
#SBATCH -N 1 --ntasks-per-node=1
#SBATCH --mem-per-cpu=15G
#SBATCH -t1:00:00


cd $SLURM_SUBMIT_DIR

module load matlab

echo $PWD 



